sonar.projectKey=dhanyn10_ostenia
sonar.organization=dhanyn10
sonar.sources=internal, main.go, frontend/src
sonar.tests=internal, frontend/src, frontend/e2e
sonar.test.inclusions=**/*_test.go, internal/testutil/**, **/*.test.tsx, **/*.spec.js
sonar.exclusions=frontend/wailsjs/**/*, frontend/src/test-setup.js
sonar.coverage.exclusions=**/*_test.go, internal/testutil/**, **/*.test.tsx, **/*.spec.js, frontend/src/test-setup.js

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.go.coverage.reportPaths=coverage-backend.out
