// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSSHSession(arg1) {
  return window['go']['backend']['App']['AddSSHSession'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['backend']['App']['CancelDownload'](arg1);
}

export function CheckProxyPorts() {
  return window['go']['backend']['App']['CheckProxyPorts']();
}

export function Close() {
  return window['go']['backend']['App']['Close']();
}

export function ConnectSSH(arg1) {
  return window['go']['backend']['App']['ConnectSSH'](arg1);
}

export function DeleteSSHSession(arg1) {
  return window['go']['backend']['App']['DeleteSSHSession'](arg1);
}

export function DeleteVersion(arg1, arg2) {
  return window['go']['backend']['App']['DeleteVersion'](arg1, arg2);
}

export function DisconnectSSH(arg1) {
  return window['go']['backend']['App']['DisconnectSSH'](arg1);
}

export function DownloadRemoteFile(arg1, arg2) {
  return window['go']['backend']['App']['DownloadRemoteFile'](arg1, arg2);
}

export function EditRemoteFile(arg1, arg2) {
  return window['go']['backend']['App']['EditRemoteFile'](arg1, arg2);
}

export function ExecuteSFTPAction(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ExecuteSFTPAction'](arg1, arg2, arg3, arg4);
}

export function ExportProfile(arg1, arg2) {
  return window['go']['backend']['App']['ExportProfile'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetInstalledApps() {
  return window['go']['backend']['App']['GetInstalledApps']();
}

export function GetPHPExtensions() {
  return window['go']['backend']['App']['GetPHPExtensions']();
}

export function GetPrerequisites() {
  return window['go']['backend']['App']['GetPrerequisites']();
}

export function GetProxyApps() {
  return window['go']['backend']['App']['GetProxyApps']();
}

export function GetRemoteCurrentPath(arg1) {
  return window['go']['backend']['App']['GetRemoteCurrentPath'](arg1);
}

export function GetRemoteFiles(arg1, arg2) {
  return window['go']['backend']['App']['GetRemoteFiles'](arg1, arg2);
}

export function GetSSHSessions() {
  return window['go']['backend']['App']['GetSSHSessions']();
}

export function GetServiceStatus(arg1) {
  return window['go']['backend']['App']['GetServiceStatus'](arg1);
}

export function ImportProfile() {
  return window['go']['backend']['App']['ImportProfile']();
}

export function InstallPluginModule(arg1, arg2) {
  return window['go']['backend']['App']['InstallPluginModule'](arg1, arg2);
}

export function InstallPrerequisite(arg1) {
  return window['go']['backend']['App']['InstallPrerequisite'](arg1);
}

export function IsAdmin() {
  return window['go']['backend']['App']['IsAdmin']();
}

export function Maximize() {
  return window['go']['backend']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['backend']['App']['Minimize']();
}

export function OpenAppsLocationFolder() {
  return window['go']['backend']['App']['OpenAppsLocationFolder']();
}

export function OpenHeidiSQL() {
  return window['go']['backend']['App']['OpenHeidiSQL']();
}

export function OpenPluginFolder(arg1) {
  return window['go']['backend']['App']['OpenPluginFolder'](arg1);
}

export function OpenProxyTerminal(arg1, arg2) {
  return window['go']['backend']['App']['OpenProxyTerminal'](arg1, arg2);
}

export function OpenServerRootFolder() {
  return window['go']['backend']['App']['OpenServerRootFolder']();
}

export function OpenServiceTerminal(arg1, arg2) {
  return window['go']['backend']['App']['OpenServiceTerminal'](arg1, arg2);
}

export function OpenTerminal(arg1) {
  return window['go']['backend']['App']['OpenTerminal'](arg1);
}

export function OpenTerminalAtPath(arg1, arg2) {
  return window['go']['backend']['App']['OpenTerminalAtPath'](arg1, arg2);
}

export function ResizeSSHTerminal(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ResizeSSHTerminal'](arg1, arg2, arg3);
}

export function SaveProxyPort(arg1, arg2) {
  return window['go']['backend']['App']['SaveProxyPort'](arg1, arg2);
}

export function SaveSSHSessions(arg1) {
  return window['go']['backend']['App']['SaveSSHSessions'](arg1);
}

export function SelectDefaultEditor() {
  return window['go']['backend']['App']['SelectDefaultEditor']();
}

export function SelectServerRoot() {
  return window['go']['backend']['App']['SelectServerRoot']();
}

export function SelectWWWRoot() {
  return window['go']['backend']['App']['SelectWWWRoot']();
}

export function SendSSHInput(arg1, arg2) {
  return window['go']['backend']['App']['SendSSHInput'](arg1, arg2);
}

export function SetApacheHTTPS(arg1) {
  return window['go']['backend']['App']['SetApacheHTTPS'](arg1);
}

export function SetDefaultEditor(arg1) {
  return window['go']['backend']['App']['SetDefaultEditor'](arg1);
}

export function SetNginxHTTPS(arg1) {
  return window['go']['backend']['App']['SetNginxHTTPS'](arg1);
}

export function SetServerRoot(arg1) {
  return window['go']['backend']['App']['SetServerRoot'](arg1);
}

export function SetWWWRoot(arg1) {
  return window['go']['backend']['App']['SetWWWRoot'](arg1);
}

export function StartAllServices() {
  return window['go']['backend']['App']['StartAllServices']();
}

export function StartService(arg1) {
  return window['go']['backend']['App']['StartService'](arg1);
}

export function StopAllServices() {
  return window['go']['backend']['App']['StopAllServices']();
}

export function StopService(arg1) {
  return window['go']['backend']['App']['StopService'](arg1);
}

export function SwitchServiceVersion(arg1, arg2) {
  return window['go']['backend']['App']['SwitchServiceVersion'](arg1, arg2);
}

export function ToggleDevTools() {
  return window['go']['backend']['App']['ToggleDevTools']();
}

export function TogglePHPExtension(arg1, arg2) {
  return window['go']['backend']['App']['TogglePHPExtension'](arg1, arg2);
}

export function UninstallPluginModule(arg1, arg2) {
  return window['go']['backend']['App']['UninstallPluginModule'](arg1, arg2);
}

export function Unmaximize() {
  return window['go']['backend']['App']['Unmaximize']();
}

export function UpdateActiveTab(arg1) {
  return window['go']['backend']['App']['UpdateActiveTab'](arg1);
}

export function UpdateSSHSession(arg1) {
  return window['go']['backend']['App']['UpdateSSHSession'](arg1);
}

export function UploadRemoteFile(arg1, arg2) {
  return window['go']['backend']['App']['UploadRemoteFile'](arg1, arg2);
}
