// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSSHSession(arg1) {
  return window['go']['backend']['App']['AddSSHSession'](arg1); // NOSONAR
}

export function CancelDownload(arg1) {
  return window['go']['backend']['App']['CancelDownload'](arg1); // NOSONAR
}

export function CheckProxyPorts() {
  return window['go']['backend']['App']['CheckProxyPorts'](); // NOSONAR
}

export function Close() {
  return window['go']['backend']['App']['Close'](); // NOSONAR
}

export function ConnectSSH(arg1) {
  return window['go']['backend']['App']['ConnectSSH'](arg1); // NOSONAR
}

export function DeleteSSHSession(arg1) {
  return window['go']['backend']['App']['DeleteSSHSession'](arg1); // NOSONAR
}

export function DeleteVersion(arg1, arg2) {
  return window['go']['backend']['App']['DeleteVersion'](arg1, arg2); // NOSONAR
}

export function DisconnectSSH(arg1) {
  return window['go']['backend']['App']['DisconnectSSH'](arg1); // NOSONAR
}

export function DownloadRemoteFile(arg1, arg2) {
  return window['go']['backend']['App']['DownloadRemoteFile'](arg1, arg2); // NOSONAR
}

export function EditRemoteFile(arg1, arg2) {
  return window['go']['backend']['App']['EditRemoteFile'](arg1, arg2); // NOSONAR
}

export function ExecuteSFTPAction(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ExecuteSFTPAction'](arg1, arg2, arg3, arg4); // NOSONAR
}

export function ExportProfile(arg1, arg2) {
  return window['go']['backend']['App']['ExportProfile'](arg1, arg2); // NOSONAR
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig'](); // NOSONAR
}

export function GetInstalledApps() {
  return window['go']['backend']['App']['GetInstalledApps'](); // NOSONAR
}

export function GetPHPExtensions() {
  return window['go']['backend']['App']['GetPHPExtensions'](); // NOSONAR
}

export function GetPrerequisites() {
  return window['go']['backend']['App']['GetPrerequisites'](); // NOSONAR
}

export function GetProxyApps() {
  return window['go']['backend']['App']['GetProxyApps'](); // NOSONAR
}

export function GetRemoteCurrentPath(arg1) {
  return window['go']['backend']['App']['GetRemoteCurrentPath'](arg1); // NOSONAR
}

export function GetRemoteFiles(arg1, arg2) {
  return window['go']['backend']['App']['GetRemoteFiles'](arg1, arg2); // NOSONAR
}

export function GetSSHSessions() {
  return window['go']['backend']['App']['GetSSHSessions'](); // NOSONAR
}

export function GetServiceStatus(arg1) {
  return window['go']['backend']['App']['GetServiceStatus'](arg1); // NOSONAR
}

export function ImportProfile() {
  return window['go']['backend']['App']['ImportProfile'](); // NOSONAR
}

export function InstallPluginModule(arg1, arg2) {
  return window['go']['backend']['App']['InstallPluginModule'](arg1, arg2); // NOSONAR
}

export function InstallPrerequisite(arg1) {
  return window['go']['backend']['App']['InstallPrerequisite'](arg1); // NOSONAR
}

export function IsAdmin() {
  return window['go']['backend']['App']['IsAdmin'](); // NOSONAR
}

export function Maximize() {
  return window['go']['backend']['App']['Maximize'](); // NOSONAR
}

export function Minimize() {
  return window['go']['backend']['App']['Minimize'](); // NOSONAR
}

export function OpenAppsLocationFolder() {
  return window['go']['backend']['App']['OpenAppsLocationFolder'](); // NOSONAR
}

export function OpenHeidiSQL() {
  return window['go']['backend']['App']['OpenHeidiSQL'](); // NOSONAR
}

export function OpenPluginFolder(arg1) {
  return window['go']['backend']['App']['OpenPluginFolder'](arg1); // NOSONAR
}

export function OpenProxyTerminal(arg1, arg2) {
  return window['go']['backend']['App']['OpenProxyTerminal'](arg1, arg2); // NOSONAR
}

export function OpenServerRootFolder() {
  return window['go']['backend']['App']['OpenServerRootFolder'](); // NOSONAR
}

export function OpenServiceTerminal(arg1, arg2) {
  return window['go']['backend']['App']['OpenServiceTerminal'](arg1, arg2); // NOSONAR
}

export function OpenTerminal(arg1) {
  return window['go']['backend']['App']['OpenTerminal'](arg1); // NOSONAR
}

export function OpenTerminalAtPath(arg1, arg2) {
  return window['go']['backend']['App']['OpenTerminalAtPath'](arg1, arg2); // NOSONAR
}

export function ResizeSSHTerminal(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ResizeSSHTerminal'](arg1, arg2, arg3); // NOSONAR
}

export function SaveProxyPort(arg1, arg2) {
  return window['go']['backend']['App']['SaveProxyPort'](arg1, arg2); // NOSONAR
}

export function SaveSSHSessions(arg1) {
  return window['go']['backend']['App']['SaveSSHSessions'](arg1); // NOSONAR
}

export function SelectDefaultEditor() {
  return window['go']['backend']['App']['SelectDefaultEditor'](); // NOSONAR
}

export function SelectServerRoot() {
  return window['go']['backend']['App']['SelectServerRoot'](); // NOSONAR
}

export function SelectWWWRoot() {
  return window['go']['backend']['App']['SelectWWWRoot'](); // NOSONAR
}

export function SendSSHInput(arg1, arg2) {
  return window['go']['backend']['App']['SendSSHInput'](arg1, arg2); // NOSONAR
}

export function SetApacheHTTPS(arg1) {
  return window['go']['backend']['App']['SetApacheHTTPS'](arg1); // NOSONAR
}

export function SetDefaultEditor(arg1) {
  return window['go']['backend']['App']['SetDefaultEditor'](arg1); // NOSONAR
}

export function SetNginxHTTPS(arg1) {
  return window['go']['backend']['App']['SetNginxHTTPS'](arg1); // NOSONAR
}

export function SetServerRoot(arg1) {
  return window['go']['backend']['App']['SetServerRoot'](arg1); // NOSONAR
}

export function SetWWWRoot(arg1) {
  return window['go']['backend']['App']['SetWWWRoot'](arg1); // NOSONAR
}

export function StartAllServices() {
  return window['go']['backend']['App']['StartAllServices'](); // NOSONAR
}

export function StartService(arg1) {
  return window['go']['backend']['App']['StartService'](arg1); // NOSONAR
}

export function StopAllServices() {
  return window['go']['backend']['App']['StopAllServices'](); // NOSONAR
}

export function StopService(arg1) {
  return window['go']['backend']['App']['StopService'](arg1); // NOSONAR
}

export function SwitchServiceVersion(arg1, arg2) {
  return window['go']['backend']['App']['SwitchServiceVersion'](arg1, arg2); // NOSONAR
}

export function ToggleDevTools() {
  return window['go']['backend']['App']['ToggleDevTools'](); // NOSONAR
}

export function TogglePHPExtension(arg1, arg2) {
  return window['go']['backend']['App']['TogglePHPExtension'](arg1, arg2); // NOSONAR
}

export function UninstallPluginModule(arg1, arg2) {
  return window['go']['backend']['App']['UninstallPluginModule'](arg1, arg2); // NOSONAR
}

export function Unmaximize() {
  return window['go']['backend']['App']['Unmaximize'](); // NOSONAR
}

export function UpdateActiveTab(arg1) {
  return window['go']['backend']['App']['UpdateActiveTab'](arg1); // NOSONAR
}

export function UpdateSSHSession(arg1) {
  return window['go']['backend']['App']['UpdateSSHSession'](arg1); // NOSONAR
}

export function UploadRemoteFile(arg1, arg2) {
  return window['go']['backend']['App']['UploadRemoteFile'](arg1, arg2); // NOSONAR
}
