// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {backend} from '../models';
import {service} from '../models';
import {plugins} from '../models';

export function AddSSHSession(arg1:config.SSHSession):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckProxyPorts():Promise<Array<backend.ProxyStatusInfo>>;

export function Close():Promise<void>;

export function ConnectSSH(arg1:config.SSHSession):Promise<void>;

export function DeleteSSHSession(arg1:string):Promise<void>;

export function DeleteVersion(arg1:string,arg2:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadRemoteFile(arg1:string,arg2:string):Promise<void>;

export function EditRemoteFile(arg1:string,arg2:string):Promise<void>;

export function ExecuteSFTPAction(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExportProfile(arg1:boolean,arg2:boolean):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetInstalledApps():Promise<Array<backend.InstalledApp>>;

export function GetPHPExtensions():Promise<Array<service.PHPExtensionInfo>>;

export function GetPrerequisites():Promise<Array<plugins.DownloadTask>>;

export function GetProxyApps():Promise<Array<backend.ProxyAppInfo>>;

export function GetRemoteCurrentPath(arg1:string):Promise<string>;

export function GetRemoteFiles(arg1:string,arg2:string):Promise<Array<service.RemoteFile>>;

export function GetSSHSessions():Promise<Array<config.SSHSession>>;

export function GetServiceStatus(arg1:string):Promise<service.ServiceDetailedInfo>;

export function ImportProfile():Promise<void>;

export function InstallPluginModule(arg1:string,arg2:string):Promise<void>;

export function InstallPrerequisite(arg1:plugins.DownloadTask):Promise<void>;

export function IsAdmin():Promise<boolean>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function OpenAppsLocationFolder():Promise<void>;

export function OpenHeidiSQL():Promise<void>;

export function OpenPluginFolder(arg1:string):Promise<void>;

export function OpenProxyTerminal(arg1:string,arg2:string):Promise<void>;

export function OpenServerRootFolder():Promise<void>;

export function OpenServiceTerminal(arg1:string,arg2:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function OpenTerminalAtPath(arg1:string,arg2:string):Promise<void>;

export function ResizeSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveProxyPort(arg1:string,arg2:number):Promise<void>;

export function SaveSSHSessions(arg1:Array<config.SSHSession>):Promise<void>;

export function SelectDefaultEditor():Promise<string>;

export function SelectServerRoot():Promise<string>;

export function SelectWWWRoot():Promise<string>;

export function SendSSHInput(arg1:string,arg2:string):Promise<void>;

export function SetApacheHTTPS(arg1:boolean):Promise<void>;

export function SetDefaultEditor(arg1:string):Promise<void>;

export function SetNginxHTTPS(arg1:boolean):Promise<void>;

export function SetServerRoot(arg1:string):Promise<void>;

export function SetWWWRoot(arg1:string):Promise<void>;

export function StartAllServices():Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopAllServices():Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function SwitchServiceVersion(arg1:string,arg2:string):Promise<void>;

export function ToggleDevTools():Promise<void>;

export function TogglePHPExtension(arg1:string,arg2:boolean):Promise<void>;

export function UninstallPluginModule(arg1:string,arg2:string):Promise<void>;

export function Unmaximize():Promise<void>;

export function UpdateActiveTab(arg1:string):Promise<void>;

export function UpdateSSHSession(arg1:config.SSHSession):Promise<void>;

export function UploadRemoteFile(arg1:string,arg2:string):Promise<void>;
