export function WindowExecJS() {}
export function WindowMinimise() {}
export function WindowMaximise() {}
export function WindowUnmaximise() {}
export function WindowClose() {}
export function Quit() {}
export function EventsOn() {}
export function EventsOff() {}
export function EventsEmit() {}
export function OpenFileDialog() {}
export function SaveFileDialog() {}
export function OpenDirectoryDialog() {}
