// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(name) {
  // @ts-ignore
  return window.go.main.App.CancelDownload(name);
}

export function DeleteVersion(taskName, version) {
  // @ts-ignore
  return window.go.main.App.DeleteVersion(taskName, version);
}

export function GetPrerequisites() {
  // @ts-ignore
  return window.go.main.App.GetPrerequisites();
}

export function InstallPrerequisite(task) {
  // @ts-ignore
  return window.go.main.App.InstallPrerequisite(task);
}

export function OpenTerminal() {
  // @ts-ignore
  return window.go.main.App.OpenTerminal();
}

export function StartAllServices() {
  // @ts-ignore
  return window.go.main.App.StartAllServices();
}

export function StartService(name) {
  // @ts-ignore
  return window.go.main.App.StartService(name);
}

export function StopAllServices() {
  // @ts-ignore
  return window.go.main.App.StopAllServices();
}

export function StopService(name) {
  // @ts-ignore
  return window.go.main.App.StopService(name);
}
