// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {service} from '../models';
import {plugins} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function CheckProxyPorts():Promise<Array<main.ProxyStatusInfo>>;

export function DeleteVersion(arg1:string,arg2:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetPHPExtensions():Promise<Array<service.PHPExtensionInfo>>;

export function GetPrerequisites():Promise<Array<plugins.DownloadTask>>;

export function GetProxyApps():Promise<Array<main.ProxyAppInfo>>;

export function GetServiceStatus(arg1:string):Promise<service.ServiceDetailedInfo>;

export function InstallPrerequisite(arg1:plugins.DownloadTask):Promise<void>;

export function IsAdmin():Promise<boolean>;

export function OpenAppsLocationFolder():Promise<void>;

export function OpenPluginFolder(arg1:string):Promise<void>;

export function OpenProxyTerminal(arg1:string,arg2:string):Promise<void>;

export function OpenServerRootFolder():Promise<void>;

export function OpenServiceTerminal(arg1:string,arg2:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function OpenTerminalAtPath(arg1:string,arg2:string):Promise<void>;

export function SaveProxyPort(arg1:string,arg2:number):Promise<void>;

export function SelectServerRoot():Promise<string>;

export function SetApacheHTTPS(arg1:boolean):Promise<void>;

export function SetNginxHTTPS(arg1:boolean):Promise<void>;

export function SetServerRoot(arg1:string):Promise<void>;

export function SetWWWRoot(arg1:string):Promise<void>;

export function StartAllServices():Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopAllServices():Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function SwitchServiceVersion(arg1:string,arg2:string):Promise<void>;

export function TogglePHPExtension(arg1:string,arg2:boolean):Promise<void>;

export function UpdateActiveTab(arg1:string):Promise<void>;
