// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * @type {any}
 */
const win = window;

export function CancelDownload(taskName) {
  return win.go.main.App.CancelDownload(taskName);
}

export function DeleteVersion(serviceName, version) {
  return win.go.main.App.DeleteVersion(serviceName, version);
}

export function GetPrerequisites() {
  return win.go.main.App.GetPrerequisites();
}

export function GetServerRoot() {
  return win.go.main.App.GetServerRoot();
}

export function GetServiceStatus(serviceName) {
  return win.go.main.App.GetServiceStatus(serviceName);
}

export function InstallPrerequisite(task) {
  return win.go.main.App.InstallPrerequisite(task);
}

export function OpenTerminal() {
  return win.go.main.App.OpenTerminal();
}

export function SetServerRoot(rootPath) {
  return win.go.main.App.SetServerRoot(rootPath);
}

export function StartAllServices() {
  return win.go.main.App.StartAllServices();
}

export function StartService(serviceName) {
  return win.go.main.App.StartService(serviceName);
}

export function StopAllServices() {
  return win.go.main.App.StopAllServices();
}

export function StopService(serviceName) {
  return win.go.main.App.StopService(serviceName);
}
