// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';
import {service} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function DeleteVersion(arg1:string,arg2:string):Promise<void>;

export function GetPrerequisites():Promise<Array<download.DownloadTask>>;

export function GetServerRoot():Promise<string>;

export function GetServiceStatus(arg1:string):Promise<service.ServiceDetailedInfo>;

export function InstallPrerequisite(arg1:download.DownloadTask):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function SelectServerRoot():Promise<string>;

export function SetServerRoot(arg1:string):Promise<void>;

export function StartAllServices():Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopAllServices():Promise<void>;

export function StopService(arg1:string):Promise<void>;
