// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function DeleteVersion(arg1, arg2) {
  return window['go']['main']['App']['DeleteVersion'](arg1, arg2);
}

export function GetPrerequisites() {
  return window['go']['main']['App']['GetPrerequisites']();
}

export function GetServerRoot() {
  return window['go']['main']['App']['GetServerRoot']();
}

export function GetServiceStatus(arg1) {
  return window['go']['main']['App']['GetServiceStatus'](arg1);
}

export function InstallPrerequisite(arg1) {
  return window['go']['main']['App']['InstallPrerequisite'](arg1);
}

export function OpenTerminal() {
  return window['go']['main']['App']['OpenTerminal']();
}

export function SetServerRoot(arg1) {
  return window['go']['main']['App']['SetServerRoot'](arg1);
}

export function StartAllServices() {
  return window['go']['main']['App']['StartAllServices']();
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopAllServices() {
  return window['go']['main']['App']['StopAllServices']();
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}
