// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';

export function CancelDownload(name:string):Promise<void>;

export function DeleteVersion(taskName:string,version:string):Promise<void>;

export function GetPrerequisites():Promise<Array<download.DownloadTask>>;

export function InstallPrerequisite(task:download.DownloadTask):Promise<void>;

export function OpenTerminal():Promise<void>;

export function StartAllServices():Promise<void>;

export function StartService(name:string):Promise<void>;

export function StopAllServices():Promise<void>;

export function StopService(name:string):Promise<void>;
