name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run Backend Tests
        run: |
          New-Item -Path "frontend/dist" -ItemType Directory -Force
          "dummy" | Out-File -FilePath "frontend/dist/index.html"
          go test -v ./...
        shell: pwsh
